server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/oris
    username: oris
    password: oris
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.xml

  freemarker:
    enabled: true
    template-loader-path: /WEB-INF/templates
    suffix: .ftl